---
output: 
  github_document:
    toc: false
    fig_width: 10.08
    fig_height: 6
tags: [r, reports]
vignette: >
  \usepackage[utf8]{inputenc}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
---

# Calendar

```{r, echo = FALSE}
knitr::opts_chunk$set(
  dpi = 600,
  collapse = TRUE,
  fig.path = "man/figures/"
)
options(knitr.kable.NA = '',
        digits = 4,
        width=60)


# Dependencies
library(insol)
```

```{r astromical_events, echo = FALSE}
# Define convenience function (needs to 'insol' package)
get_dates_atronomical <- function(year=2013){
  dates <- seq(ISOdate(year, 1, 1), ISOdate(year, 12, 31), by='day')
  days <- insol::JD(dates)
  data <- insol::declination(days)

  # Solstice
  solstice_winter <- as.Date(dates[which(data==min(data))])
  solstice_summer <- as.Date(dates[which(data==max(data))])

  # Equinox
  equinox_spring = uniroot(insol::declination, days[c(1,180)])$root
  equinox_spring = as.Date(dates[insol::daydoy(insol::JD(equinox_spring, inv=TRUE))])

  equinox_autumn = uniroot(insol::declination, days[c(180,360)])$root
  equinox_autumn = as.Date(dates[insol::daydoy(JD(equinox_autumn,inv=TRUE))])

  list("Solstice_Summer"=solstice_summer, 
       "Solstice_Winter"=solstice_winter,
       "Equinox_Autumn"=equinox_autumn, 
       "Equinox_Spring"=equinox_spring)
}
```

```{r dates_celebrations, echo = FALSE}
get_dates_celebrations <- function(year=2020){
  astro <- get_dates_atronomical(year=year)
  
  # Rise and Fall
  # TODO
  
  # Dark nights/Bright days
  # TODO
  
  # Celebrations
  c("Fallfest"=astro$Solstice_Summer,
    "Thanksday"=as.Date(paste0(year, "-08-01")),
    "Moonfest"=astro$Equinox_Autumn,
    "Harvestday"=as.Date(paste0(year, "-10-31")),
    "Deadsnight"=as.Date(paste0(year, "-11-01")),
    "Risefest"=astro$Solstice_Winter,
    "Preparationday"=as.Date(paste0(year, "-02-01")),
    "Sunfest"=astro$Equinox_Spring,
    "Loversnight"=as.Date(paste0(year, "-04-30")),
    "Lifesday"=as.Date(paste0(year, "-05-01")))
}
```


```{r find_closest, echo = FALSE, results='asis'}
today <- Sys.Date()
year <- as.numeric(format(today, "%Y"))

dates <- as.Date(c())
for(y in c(year, year + 1)){
  dates <- c(dates, get_dates_celebrations(as.character(y)))
  d <- today - dates
  dates <- dates[d <= 0]
}

d <- today - dates
next_date <- which.max(d)

print(paste0("The next celebration is [**", names(next_date), "**](https://github.com/RealityBending/Calendar#", names(next_date), ") in **", abs(as.numeric(d[next_date])), "** days."))
```

## Celebrations

### Fallfest

Description.

### Thanksday

Description.

### Moonfest

Description.

### Harvestday

Description.

### Deadsnight

Description.

### Risefest

Description.

### Preparationday

Description.

### Sunfest

Description.

### Loversnight

Description.

### Lifesday

Description.

